#!/bin/bash
## Start my calendar (calcurse) when X start.

CAL()
{
	## Check if the daemon is running, and launch it if not.
	pidof calcurse>/dev/null
	[[ ${?} -ne "0" ]] && calcurse --daemon
	## Send notification with the today's appointements.
	notify-send -u critical "$(calcurse -Q)"
}

RED="\e[31m"
RC="\e[0m"

REQUIREMENTS="notify-send calcurse"
which ${REQUIREMENTS}>/dev/null

if [[ ${?} -eq "0" ]]
	then
		CAL
	else
		echo -e "${RED}\n To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}${RC}\n${RED} Exiting...${RC}\n"
fi
