#!/bin/bash
## - Install basics tools.
## - Configure a Kali-Linux live system for remote access.

RC="\e[0m"
RED="\e[31m"
GREEN="\e[32m"

DISTRO=$(cat /etc/os-release | grep PRETTY_NAME | cut -d "=" -f 2 | sed 's/"//g')
PACKAGES="htop bpytop xterm xrdp openssh-server zaproxy burpsuite maltego maltego-teeth metasploit-framework nmap nano wireshark aircrack-ng tor ccze ncdu"

INSTALL_PACKAGES()
{
	apt-get update
	apt-get install -f -y ${PACKAGES}
}

SERVICES()
{
	## SSH
	systemctl enable --now ssh.service
	## RDP
	systemctl enable --now xrdp.service
	## Login manager
	systemctl disable --now lightdm.service
}

CLEAR_APT_ARCHIVES()
{
	## Removes apt archives after downloading and installing them.
	## On live USB space is precious!
	apt-get purge --autoremove -f -y
	apt-get clean -y
	apt-get autoclean -y
}

## Check if root?
if [ "$EUID" -ne 0 ]
	then
		echo -e "${RED}This script must be run as root!\nExiting...${RC}"
	    exit 1
	else
		if [[ ${DISTRO} != "Kali GNU/Linux Rolling" ]]
			then
				echo -e "${RED}You are not on a Kali-Linux system\nExiting...${RC}"
				exit 1
			else
				INSTALL_PACKAGES
				CLEAR_APT_ARCHIVES
				SERVICES
				echo -e "${GREEN}Done!${RC}"
		fi
fi
