#!/bin/bash
# Install ZSH adn my personal configuration for it.

# Set color
RESET_COLOR="\e[0m"
RED="\e[31m"
GREEN="\e[32m"

# Check if root
if [ "$EUID" -ne 0 ]
    then
        echo -e "${RED}This script must be runned as root${RESET_COLOR}"
        exit
fi

# Check for requirements
apt install -y curl zsh zsh-common zsh-syntax-highlighting zsh-autosuggestions

USER="lespink"
GIT_PERSO_PATH="/opt/utilities"

# Install oh my zsh to root and home
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp -vrf /root/.oh-my-zsh /home/${USER}
cd ~/.oh-my-zsh/plugins
git clone https://github.com/zsh-users/zsh-completions.git
git clone https://github.com/zsh-users/zsh-autosuggestions.git

# Copy ZSH config to home
cp -vrf ${GIT_PERSO_PATH}/dot-files/.zshrc /home/${USER}
cp -vrf ${GIT_PERSO_PATH}/dot-files/.zshrc /home/root

